name: Python check

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test_package:
    name: Test ${{ matrix.os }} Python ${{ matrix.python_version }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["macos-11", "ubuntu-20.04", "windows-latest"]
        python_version: ["3.7", "3.8", "3.9", "3.10", "3.11"]
    steps:
        - name: Setup python
          uses: actions/setup-python@v2
          with:
            python-version: ${{ matrix.python_version }}
            architecture: x64
        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            pip install flake8
        - name: Look for major issues with flake8
          run: |
            flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        - name: Make sure Python code is all compilable
          run: |
            python -m compileall